### PR TITLE
Use 2020 logo for og meta tags

### PR DESCRIPTION
**Pull request by hajinlee**
Update asset name in og meta tags

### CODE REVIEW

**Comment by neagle** [comment]
Hajin, I'm so glad that you got the PR process all figured out. Thanks for your PR!

I'm glad that someone cares about the `og:image` situation: whenever we post links to the Congress site on Facebook/Twitter/whatever, that's what pops up, and we want it to be current. The reason I had it set to check for the existence of an actual `og-image.png` in the current year's folder is that the open graph image should be a particular size—1200x630px. So for the 2018 Congress, I made a custom image that used the logo and also had some background texture.

image

So what I'd love for us to do is just add a `2020` folder inside images, and put a new `og-image.png` file inside it that's also 1200x630px. Would you have any interest in making that image? It *could* be as simple as a white or green background with the logo in front of it.

But wherever possible, I'd like to get our code to where it doesn't require year-to-year updating, and instead just reacts correctly to the presence or absence of file resources.

**Comment by hajinlee** [comment]
Didn't know about the image size restrictions! Updated PR with your suggestion.

**Comment by neagle** [comment]
This is great, Hajin—I'll push this change to the live site shortly. Congrats on your first PR! 🥂

**Comment by neagle** [comment]
Launched. You can check out the new `og:image` using the [Facebook debug tool](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.gocongress.org%2F). Thanks again, @hajinlee!

**Pull request merged**
